package homeworks.dmytro_k.hw_2023.hw_04_05_23_v2;

public enum SubCategory {
    SMARTPHONE,
    PHONE,
    GAMELAPTOP,
    BUSINESSLAPTOP,
    OFFICEMOUSE,
    LAPTOPMOUSE,
    GAMEMOUSE,
    TV4k,
    SMARTTV,
    ANDROIDTV,
    WIRELESSCHARGER,
    SOLARCHARGER,
    QUICKCHARGER,
    GAMEKEYBOARD,
    OFFICEKEYBOARD,
    TVKEYBOARD;
}
